on:
  workflow_dispatch:

name: get-data
jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://jsonhub.pages.dev
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Download companyInfo
        run: |-
          curl -L -o data.csv "https://docs.google.com/spreadsheets/d/e/2PACX-1vQk-ywyl8AsCBz0L6_eMvIOVbIpYWh-aRv-l2a2riubpXYiH-0Nbv2nqE1c7Fs5YwNg-VjlZVFk3qdC/pubhtml?gid=970624538&single=true&output=csv&headers=0&range=A2:ZZ"

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
